export const COLLAPSE_MENU = 'COLLAPSE_MENU'
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE'

export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE'
export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const ACCOUNT_INITIALIZE = 'ACCOUNT_INITIALIZE'

/** WHATSAPP CONNECTION */
export const WHATSAPP_CONNECTION = 'WHATSAPP_CONNECTION'
/** CLIENT  */
export const CLIENT_SEE_ALL = 'CLIENT_SEE_ALL'
export const CLIENT_FILTER = 'CLIENT_FILTER'
/** PIECE  */
export const PIECE_SEE_ALL = 'PIECE_SEE_ALL'
export const PIECE_FILTER = 'PIECE_FILTER'
/** SERVICE  */
export const SERVICE_SEE_ALL = 'SERVICE_SEE_ALL'
export const SERVICE_FILTER = 'SERVICE_FILTER'
/** MODEL  */
export const MODEL_SEE_ALL = 'MODEL_SEE_ALL'
export const MODEL_FILTER = 'MODEL_FILTER'
/** SERVICE ORDER */
export const SERVICE_ORDER_SEE_ALL = 'SERVICE_ORDER_SEE_ALL'
export const SERVICE_ORDER_FILTER = 'SERVICE_ORDER_FILTER'
export const SERVICE_ORDER_CREATE = 'SERVICE_ORDER_CREATE'
/** EQUIPAMENT  */
export const EQUIPAMENT_SEE_ALL = 'EQUIPAMENT_SEE_ALL'
export const EQUIPAMENT_FILTER = 'EQUIPAMENT_FILTER'
/** LAYOUT */
export const LAYOUT_TITLE_PAGE = 'LAYOUT_TITLE_PAGE'
export const LAYOUT_MAKE_REQUEST = 'LAYOUT_MAKE_REQUEST'
export const LAYOUT_IS_MODIFIED_FIELDS = 'LAYOUT_IS_MODIFIED_FIELDS'
